name: Uptime Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Ping your API
        run: |
          echo "Checking uptime for your API..."
          curl -I https://your-app-name.onrender.com || echo "API is down"
